// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using grefurBackend.Context;

#nullable disable

namespace grefurBackend.Migrations.Timescale
{
    [DbContext(typeof(TimescaleContext))]
    [Migration("20260212201208_UpdateSensorReadingKeyw")]
    partial class UpdateSensorReadingKeyw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("grefurBackend.Models.SensorReading", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text")
                        .HasColumnName("customerId");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deviceId");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Timestamp", "Topic", "CustomerId");

                    b.ToTable("sensorReadings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
