// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grefurBackend.Context;

#nullable disable

namespace grefurBackend.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20260228165515_AddVirtualSensorSupportUpdate4")]
    partial class AddVirtualSensorSupportUpdate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("grefurBackend.Models.AlarmConfiguration.MlAlarmConfiguration", b =>
                {
                    b.Property<string>("MlAlarmId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("DeviationProbabilityThreshold")
                        .HasColumnType("double");

                    b.PrimitiveCollection<string>("FeatureMeasurementIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("FeatureOrder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastTrainedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModelUri")
                        .HasColumnType("longtext");

                    b.Property<int>("ModelVersion")
                        .HasColumnType("int");

                    b.Property<int>("SampleIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TargetMeasurementId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrainingFrequency")
                        .HasColumnType("int");

                    b.HasKey("MlAlarmId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MlAlarmConfigurations");
                });

            modelBuilder.Entity("grefurBackend.Models.GrefurCustomer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AlarmSubscription")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailOfOrganization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LogSubscription")
                        .HasColumnType("int");

                    b.Property<int>("NotificationSubscription")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("GrefurCustomers");
                });

            modelBuilder.Entity("grefurBackend.Models.GrefurDevice", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExpectedServerCertificateThumbprint")
                        .HasColumnType("longtext");

                    b.Property<string>("HardwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeletedByCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNested")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSignOfLife")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RemoteAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceValidationToken")
                        .HasColumnType("longtext");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DeviceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("GrefurDevices");

                    b.HasDiscriminator<string>("DeviceCategory").HasValue("Physical");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("grefurBackend.Models.GrefurUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("GrefurUsers");
                });

            modelBuilder.Entity("grefurBackend.Models.VirtualSensorValue", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastValue")
                        .HasColumnType("longtext");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.HasKey("ValueId");

                    b.HasIndex("DeviceId");

                    b.ToTable("VirtualSensorValues");
                });

            modelBuilder.Entity("grefurBackend.Models.VirtualGrefurDevice", b =>
                {
                    b.HasBaseType("grefurBackend.Models.GrefurDevice");

                    b.Property<string>("ApiProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApiProviderUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomHeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FrontendHeader")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("NextScheduledFetchUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestBodyJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestHeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Virtual");
                });

            modelBuilder.Entity("grefurBackend.Models.AlarmConfiguration.MlAlarmConfiguration", b =>
                {
                    b.HasOne("grefurBackend.Models.GrefurCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("grefurBackend.Models.GrefurCustomer", b =>
                {
                    b.OwnsOne("grefurBackend.Models.UsageStats", "LoggedPointsUsage", b1 =>
                        {
                            b1.Property<string>("GrefurCustomerCustomerId")
                                .HasColumnType("varchar(255)");

                            b1.Property<long>("LastMonth")
                                .HasColumnType("bigint");

                            b1.Property<long>("LastQuarter")
                                .HasColumnType("bigint");

                            b1.Property<long>("LastYear")
                                .HasColumnType("bigint");

                            b1.Property<long>("ThisMonth")
                                .HasColumnType("bigint");

                            b1.Property<long>("Total")
                                .HasColumnType("bigint");

                            b1.HasKey("GrefurCustomerCustomerId");

                            b1.ToTable("GrefurCustomers");

                            b1.WithOwner()
                                .HasForeignKey("GrefurCustomerCustomerId");
                        });

                    b.OwnsOne("grefurBackend.Models.NotificationUsage", "NotificationUsage", b1 =>
                        {
                            b1.Property<string>("GrefurCustomerCustomerId")
                                .HasColumnType("varchar(255)");

                            b1.HasKey("GrefurCustomerCustomerId");

                            b1.ToTable("GrefurCustomers");

                            b1.WithOwner()
                                .HasForeignKey("GrefurCustomerCustomerId");

                            b1.OwnsOne("grefurBackend.Models.UsageStats", "Email", b2 =>
                                {
                                    b2.Property<string>("NotificationUsageGrefurCustomerCustomerId")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<long>("LastMonth")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("LastQuarter")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("LastYear")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("ThisMonth")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Total")
                                        .HasColumnType("bigint");

                                    b2.HasKey("NotificationUsageGrefurCustomerCustomerId");

                                    b2.ToTable("GrefurCustomers");

                                    b2.WithOwner()
                                        .HasForeignKey("NotificationUsageGrefurCustomerCustomerId");
                                });

                            b1.OwnsOne("grefurBackend.Models.UsageStats", "Sms", b2 =>
                                {
                                    b2.Property<string>("NotificationUsageGrefurCustomerCustomerId")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<long>("LastMonth")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("LastQuarter")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("LastYear")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("ThisMonth")
                                        .HasColumnType("bigint");

                                    b2.Property<long>("Total")
                                        .HasColumnType("bigint");

                                    b2.HasKey("NotificationUsageGrefurCustomerCustomerId");

                                    b2.ToTable("GrefurCustomers");

                                    b2.WithOwner()
                                        .HasForeignKey("NotificationUsageGrefurCustomerCustomerId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Sms")
                                .IsRequired();
                        });

                    b.Navigation("LoggedPointsUsage")
                        .IsRequired();

                    b.Navigation("NotificationUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("grefurBackend.Models.GrefurDevice", b =>
                {
                    b.HasOne("grefurBackend.Models.GrefurCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("grefurBackend.Models.VirtualSensorValue", b =>
                {
                    b.HasOne("grefurBackend.Models.VirtualGrefurDevice", null)
                        .WithMany("SensorValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grefurBackend.Models.VirtualGrefurDevice", b =>
                {
                    b.Navigation("SensorValues");
                });
#pragma warning restore 612, 618
        }
    }
}
